# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('slug', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Slug')),
                ('csv', models.TextField(blank=True, verbose_name='Csv data')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Last update')),
                ('modelnames', models.CharField(blank=True, help_text='List of model names: ex: User,Group', max_length=200, verbose_name='Associated models')),
                ('generator', models.CharField(blank=True, max_length=120, verbose_name='Generator')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
    ]
