# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='fields_definition',
            field=models.TextField(blank=True, verbose_name='Fields definition'),
        ),
    ]
