# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabular', '0002_table_fields_definition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='csv',
        ),
        migrations.RemoveField(
            model_name='table',
            name='fields_definition',
        ),
        migrations.AddField(
            model_name='table',
            name='html',
            field=models.TextField(blank=True, verbose_name='Html'),
        ),
    ]
